title: Conecting LEDs to a Raspberry Pi
hero_image: images/banner.png
description: Connect and LED to a Raspberry Pi
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: "physical computing"
technologies: "physical computing"
steps:
  - title: Connecting LEDs to a Raspberry Pi
