title: Coonecting LEDs to a Raspberry Pi
hero_image: images/banner.png
description: rpi-physical-connect-led description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1
published: false
ingredient: false
steps:
  - title: Connecting LEDs to a Raspberry Pi
